config/routes.rb
Rails.application.routes.draw do
  root :to => 'questions#index'

  get "/log-in" => "sessions#new"
  post "/log-in" => "sessions#create"
  get "/log-out" => "sessions#destroy", as: :log_out

  resources :users
  # resources :sessions

  resources :questions

  resources :questions do
    resources :responses
  end
end

app/models/question.rb
class Question < ActiveRecord::Base
  validates :title, :presence => true
  validates :description, :presence => true
  validates :author, :presence => true

  belongs_to :user
  has_many :responses
end

app/models/response.rb
class Response < ActiveRecord::Base
  validates :response, :presence => true
  validates :name, :presence => true

  belongs_to :user
  belongs_to :question
end

app/models/user.rb
class User < ActiveRecord::Base
  validates_presence_of :email, :password
  has_many :questions
  has_many :responses

  attr_accessor :password
  validates_confirmation_of :password
  before_save :encrypt_password

  def encrypt_password
    self.password_salt = BCrypt::Engine.generate_salt
    self.password_hash = BCrypt::Engine.hash_secret(password, password_salt)
  end

  def self.authenticate(email, password)
    user = User.where(email: email).first
      if user && user.password_hash == BCrypt::Engine.hash_secret(password, user.password_salt)
        user
      else
        nil
      end
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

  def authorize
    redirect_to log_in_url, alert: "Not authorized" if current_user.nil?
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_filter :authorize, only: [:edit, :update, :destroy]

  def index
    @questions = Question.all
  end

  def show
  @question = Question.find(params[:id])
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(question_params)
    if @question.save
      redirect_to questions_path
    else
      render :new
    end
  end

  def edit
    @question = Question.find(params[:id])
  end

  def update
    @question = Question.find(params[:id])
    if @question.update(question_params)
      redirect_to questions_path(@question)
    else
      render :edit
    end
  end

  def destroy
    @question = Question.find(params[:id])
    @question.destroy
    redirect_to questions_path
  end

  private
  def question_params
    params.require(:question).permit(:title, :description, :author)
  end

end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController
  def new
    @question = Question.find(params[:question_id])
    @response = @question.responses.new
  end

  def create
    @question = Question.find(params[:question_id])
    @response = @question.responses.new(response_params)
    if @response.save
      redirect_to question_path(@response.question)
    else
      render :new
    end
  end

  private
  def response_params
    params.require(:response).permit(:response, :name)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    @user = User.authenticate(params[:email], params[:password])

      if @user
        flash[:notice] = "You've been logged in"
        session[:user_id] = @user.id
        redirect_to "/"
      else
        flash[:alert] = "There was a problem logging you in"
        redirect_to log_in_path
      end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You've been logged out successfully."
    redirect_to "/"
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      #send email
      UserMailer.signup_confirmation(@user).deliver

      session[:user_id] = @user.id
      flash[:notice] = "Welcome to the site!"
    redirect_to "/"
    else
      flash[:alert] = "There was a problem creating your account. Please try again."
      redirect_to :back
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private
  def user_params
    params.require(:user).permit(:email, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Stack Overflow Clone</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <div class='container'>
    <%= flash[:alert] %>
    <%= flash[:notice] %>

    <% if current_user %>
      Logged in as <%= current_user.email %>.
      <%= link_to "Log Out", log_out_path %>
    <% else %>
      <%= link_to "Sign Up", new_user_path %> or
      <%= link_to "Log In", log_in_path %>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>

app/views/questions/_form.html.erb
<%= render "layouts/errors", :object => @question %>

<%= form_for @question do |f| %>
  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :description %>
  <%= f.text_field :description %>

  <%= f.label :author %>
  <%= f.text_field :author %>

  <%= f.submit  %>
<% end %>

app/views/questions/edit.html.erb
<h1>Update Question</h1>

<%= render 'form' %>

app/views/questions/index.html.erb
<h1>Questions</h1>

<ul>
  <% @questions.each do |question| %>
    <li><%= link_to question.title, question_path(question) %></li>
  <% end %>
</ul>

<%= link_to "New Question", new_question_path %>

app/views/questions/new.html.erb
<h1>New Question</h1>

<%= render 'form' %>

<p><%= link_to "Return Home", questions_path %></p>

app/views/questions/show.html.erb
<h1><%= @question.title %></h1>

<% if @question.responses.any? %>
  <h4>Here are the responses for this question:</h4>

  <ul>
    <% @question.responses.each do |response| %>
      <li><%= response.response %></li>
      <li>by: <%= response.name %></li>
      <li>on: <%= response.created_at %></li>
    <% end %>
  </ul>
<% else %>
  <p>There are no responses yet!</p>
<% end %>

<p><%= link_to "Update Question", edit_question_path(@question) %></p>

<p><%= link_to "Delete Question", question_path(@question), :method => 'delete' %></p>

<p><%= link_to "Add a response", new_question_response_path(@question) %></p>

<p><%= link_to "Return Home", questions_path %></p>

app/views/responses/_form.html.erb
<%= render "layouts/errors", :object => @response %>

<%= form_for [@question, @response] do |f| %>
  <%= f.label :response %>
  <%= f.text_field :response %>

  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.submit  %>
<% end %>

app/views/responses/new.html.erb
<h1><%= @question.title %></h1>

<%= render 'form' %>

app/views/users/new.html.erb
<h1>Sign Up</h1>
  <%=form_for User.new do |f| %>
  <%=f.label :email %>
  <%=f.text_field :email %>

  <%=f.label :password %>
  <%=f.password_field :password %>

  <%=f.label :password_confirmation %>
  <%=f.password_field :password_confirmation %>

  <%=f.submit "Click Here" %>
<%end%>